"""Frozen, normalized CLI help output for the root parser and every subcommand.

The argparse help text is part of the documented CLI surface. Any
change to it is a breaking change for users. These tests compare
against the checked-in golden files in ``tests/fixtures/golden/``,
which capture the normalized help for the root parser and every
subcommand. The golden files are regenerated by
``tests/fixtures/_builders.py::build_golden_help``.
"""

from __future__ import annotations

import argparse
import contextlib
import io
import re
from pathlib import Path

import pytest

from osm_polygon_wikidata_only.cli.parser import build_parser

FIXTURE_ROOT = Path(__file__).resolve().parent.parent / "fixtures"
GOLDEN = FIXTURE_ROOT / "golden"


class _FrozenFormatter(argparse.HelpFormatter):
    """Formatter used to keep golden help output deterministic."""

    def __init__(self, prog: str) -> None:
        super().__init__(prog, width=100, max_help_position=30)


def _capture_help(parser: argparse.ArgumentParser, prog_args: list[str]) -> str:
    """Invoke ``--help`` and capture the stdout output."""
    buffer = io.StringIO()
    with contextlib.redirect_stdout(buffer):
        with pytest.raises(SystemExit) as exc:
            parser.parse_args([*prog_args, "--help"])
    assert exc.value.code == 0
    text = buffer.getvalue()
    text = re.sub(r"^usage:\s+\S+\s+", "usage: PROG ", text, flags=re.MULTILINE)
    text = re.sub(r"[ \t]{2,}", " ", text)
    return "\n".join(line.rstrip() for line in text.splitlines()).rstrip() + "\n"


def _parser_with_frozen_formatter() -> argparse.ArgumentParser:
    """Build the production parser with the frozen formatter width."""
    parser = build_parser()
    _freeze_formatters(parser)
    return parser


def _freeze_formatters(parser: argparse.ArgumentParser) -> None:
    """Apply the frozen formatter to *parser* and every nested subparser."""
    parser.formatter_class = _FrozenFormatter
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            for sub_parser in action.choices.values():
                _freeze_formatters(sub_parser)


@pytest.fixture(scope="module")
def help_outputs() -> dict[str, str]:
    parser = _parser_with_frozen_formatter()
    return {
        "root": _capture_help(parser, []),
        "process-pbf": _capture_help(parser, ["process-pbf"]),
        "process-dir": _capture_help(parser, ["process-dir"]),
        "sync-dir": _capture_help(parser, ["sync-dir"]),
        "split-v2-sentences": _capture_help(parser, ["split-v2-sentences"]),
        "augment-region": _capture_help(parser, ["augment-region"]),
        "augment-dir": _capture_help(parser, ["augment-dir"]),
        "language-splits": _capture_help(parser, ["language-splits"]),
        "publish-language-splits": _capture_help(parser, ["publish-language-splits"]),
        "release-stats": _capture_help(parser, ["release-stats"]),
        "enforce-integrity": _capture_help(parser, ["enforce-integrity"]),
        "audit-remote": _capture_help(parser, ["audit-remote"]),
        "trackio-snapshot": _capture_help(parser, ["trackio-snapshot"]),
        "grid5000": _capture_help(parser, ["grid5000"]),
        "grid5000-controller": _capture_help(parser, ["grid5000", "controller"]),
        "grid5000-job": _capture_help(parser, ["grid5000", "job"]),
        "audit-containment": _capture_help(parser, ["audit-containment"]),
    }


def test_root_help_frozen(help_outputs: dict[str, str]) -> None:
    golden_path = GOLDEN / "cli_help_root.txt"
    assert golden_path.exists(), f"missing golden help file: {golden_path}"
    assert help_outputs["root"] == golden_path.read_text(encoding="utf-8")


def test_release_stats_help_frozen(help_outputs: dict[str, str]) -> None:
    golden_path = GOLDEN / "cli_help_release-stats.txt"
    assert golden_path.exists(), f"missing golden help file: {golden_path}"
    assert help_outputs["release-stats"] == golden_path.read_text(encoding="utf-8")


def test_process_pbf_help_frozen(help_outputs: dict[str, str]) -> None:
    golden_path = GOLDEN / "cli_help_process-pbf.txt"
    assert golden_path.exists(), f"missing golden help file: {golden_path}"
    assert help_outputs["process-pbf"] == golden_path.read_text(encoding="utf-8")


def test_process_dir_help_frozen(help_outputs: dict[str, str]) -> None:
    golden_path = GOLDEN / "cli_help_process-dir.txt"
    assert golden_path.exists(), f"missing golden help file: {golden_path}"
    assert help_outputs["process-dir"] == golden_path.read_text(encoding="utf-8")


def test_sync_dir_help_frozen(help_outputs: dict[str, str]) -> None:
    golden_path = GOLDEN / "cli_help_sync-dir.txt"
    assert golden_path.exists(), f"missing golden help file: {golden_path}"
    assert help_outputs["sync-dir"] == golden_path.read_text(encoding="utf-8")


def test_sentence_split_help_frozen(help_outputs: dict[str, str]) -> None:
    golden_path = GOLDEN / "cli_help_split-v2-sentences.txt"
    assert golden_path.exists(), f"missing golden help file: {golden_path}"
    assert help_outputs["split-v2-sentences"] == golden_path.read_text(encoding="utf-8")


def test_augment_region_help_frozen(help_outputs: dict[str, str]) -> None:
    golden_path = GOLDEN / "cli_help_augment-region.txt"
    assert golden_path.exists(), f"missing golden help file: {golden_path}"
    assert help_outputs["augment-region"] == golden_path.read_text(encoding="utf-8")


def test_augment_dir_help_frozen(help_outputs: dict[str, str]) -> None:
    golden_path = GOLDEN / "cli_help_augment-dir.txt"
    assert golden_path.exists(), f"missing golden help file: {golden_path}"
    assert help_outputs["augment-dir"] == golden_path.read_text(encoding="utf-8")


def test_language_splits_help_frozen(help_outputs: dict[str, str]) -> None:
    golden_path = GOLDEN / "cli_help_language-splits.txt"
    assert golden_path.exists(), f"missing golden help file: {golden_path}"
    assert help_outputs["language-splits"] == golden_path.read_text(encoding="utf-8")


def test_publish_language_splits_help_frozen(help_outputs: dict[str, str]) -> None:
    golden_path = GOLDEN / "cli_help_publish-language-splits.txt"
    assert golden_path.exists(), f"missing golden help file: {golden_path}"
    assert help_outputs["publish-language-splits"] == golden_path.read_text(encoding="utf-8")


def test_root_help_lists_every_subcommand(help_outputs: dict[str, str]) -> None:
    text = help_outputs["root"]
    for command in (
        "process-pbf",
        "process-dir",
        "sync-dir",
        "split-v2-sentences",
        "augment-region",
        "augment-dir",
        "language-splits",
        "publish-language-splits",
        "release-stats",
        "enforce-integrity",
        "audit-remote",
        "trackio-snapshot",
        "grid5000",
        "audit-containment",
    ):
        assert command in text


@pytest.mark.parametrize(
    "name",
    [
        "enforce-integrity",
        "audit-remote",
        "trackio-snapshot",
        "grid5000",
        "grid5000-controller",
        "grid5000-job",
        "audit-containment",
    ],
)
def test_tool_help_frozen(help_outputs: dict[str, str], name: str) -> None:
    golden_path = GOLDEN / f"cli_help_{name}.txt"
    assert golden_path.exists(), f"missing golden help file: {golden_path}"
    assert help_outputs[name] == golden_path.read_text(encoding="utf-8")


def test_every_subcommand_has_a_golden_help_file(help_outputs: dict[str, str]) -> None:
    sub_action = next(
        action
        for action in build_parser()._actions
        if isinstance(action, argparse._SubParsersAction)
    )
    assert set(sub_action.choices) <= set(help_outputs)


def test_root_help_includes_top_level_description(help_outputs: dict[str, str]) -> None:
    text = help_outputs["root"]
    assert (
        "Build a Hugging Face dataset of OSM polygons with Wikidata, Wikipedia, and Wikivoyage."
        in text
    )
